version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "1338:1338"
    volumes:
      - .:/server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sharetrip
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      NODE_ENV: "development"

  # Database
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sharetrip
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
